### ISSUE TITLE
please include license texts for Zlib and Apache-2.0

### ISSUE THREAD

**Issue by decathorpe** [Soveu/tinyvec_macros#1]
According to the Cargo.toml file, this project is licensed under `MIT OR Apache-2.0 OR Zlib` licenses, but the LICENSE file only contains the MIT license.

Both the Apache-2.0 and Zlib licenses require that the license text is shipped with source code, and this is causing problems for downstream projects (for example, linux distribution packages for your project).

See: https://choosealicense.com/licenses/zlib/ and https://choosealicense.com/licenses/apache-2.0/ (hovering the "License and copyright notice" under "Conditions" reveals the specific requirement)

Please consider adding those license texts (and probably rename `LICENSE` file to `LICENSE-MIT`).

**Comment by Soveu** [comment]
The license files have been added
